// -------------------------------------------------------------
//
// Module: fir_50_3
// Generated by MATLAB(R) 9.7 and Filter Design HDL Coder 3.1.6.
// Generated on: 2022-05-22 17:28:08
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: E:\TD\workspace
// Name: fir_50_3
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 32
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s16,8 -> [-128 128)
// Input             : s12,0 -> [-2048 2048)
// Filter Internals  : Full Precision
//   Output          : s21,8 -> [-4096 4096)  (auto determined)
//   Product         : s18,8 -> [-512 512)  (auto determined)
//   Accumulator     : s21,8 -> [-4096 4096)  (auto determined)
//   Round Mode      : No rounding
//   Overflow Mode   : No overflow
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module fir_50_3
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [11:0] filter_in; //sfix12
  output  signed [20:0] filter_out; //sfix21_En8

////////////////////////////////////////////////////////////////
//Module Architecture: fir_50_3
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b1111111111111111; //sfix16_En8
  parameter signed [15:0] coeff2 = 16'b1111111111111110; //sfix16_En8
  parameter signed [15:0] coeff3 = 16'b1111111111111101; //sfix16_En8
  parameter signed [15:0] coeff4 = 16'b1111111111111011; //sfix16_En8
  parameter signed [15:0] coeff5 = 16'b1111111111111010; //sfix16_En8
  parameter signed [15:0] coeff6 = 16'b1111111111111010; //sfix16_En8
  parameter signed [15:0] coeff7 = 16'b1111111111111010; //sfix16_En8
  parameter signed [15:0] coeff8 = 16'b1111111111111100; //sfix16_En8
  parameter signed [15:0] coeff9 = 16'b0000000000000000; //sfix16_En8
  parameter signed [15:0] coeff10 = 16'b0000000000000101; //sfix16_En8
  parameter signed [15:0] coeff11 = 16'b0000000000001011; //sfix16_En8
  parameter signed [15:0] coeff12 = 16'b0000000000010010; //sfix16_En8
  parameter signed [15:0] coeff13 = 16'b0000000000011010; //sfix16_En8
  parameter signed [15:0] coeff14 = 16'b0000000000100000; //sfix16_En8
  parameter signed [15:0] coeff15 = 16'b0000000000100101; //sfix16_En8
  parameter signed [15:0] coeff16 = 16'b0000000000100111; //sfix16_En8
  parameter signed [15:0] coeff17 = 16'b0000000000100111; //sfix16_En8
  parameter signed [15:0] coeff18 = 16'b0000000000100101; //sfix16_En8
  parameter signed [15:0] coeff19 = 16'b0000000000100000; //sfix16_En8
  parameter signed [15:0] coeff20 = 16'b0000000000011010; //sfix16_En8
  parameter signed [15:0] coeff21 = 16'b0000000000010010; //sfix16_En8
  parameter signed [15:0] coeff22 = 16'b0000000000001011; //sfix16_En8
  parameter signed [15:0] coeff23 = 16'b0000000000000101; //sfix16_En8
  parameter signed [15:0] coeff24 = 16'b0000000000000000; //sfix16_En8
  parameter signed [15:0] coeff25 = 16'b1111111111111100; //sfix16_En8
  parameter signed [15:0] coeff26 = 16'b1111111111111010; //sfix16_En8
  parameter signed [15:0] coeff27 = 16'b1111111111111010; //sfix16_En8
  parameter signed [15:0] coeff28 = 16'b1111111111111010; //sfix16_En8
  parameter signed [15:0] coeff29 = 16'b1111111111111011; //sfix16_En8
  parameter signed [15:0] coeff30 = 16'b1111111111111101; //sfix16_En8
  parameter signed [15:0] coeff31 = 16'b1111111111111110; //sfix16_En8
  parameter signed [15:0] coeff32 = 16'b1111111111111111; //sfix16_En8

  // Signals
  reg  signed [11:0] delay_pipeline [0:31] ; // sfix12
  wire signed [17:0] product32; // sfix18_En8
  wire signed [12:0] mulpwr2_temp; // sfix13
  wire signed [17:0] product31; // sfix18_En8
  wire signed [12:0] mulpwr2_temp_1; // sfix13
  wire signed [17:0] product30; // sfix18_En8
  wire signed [27:0] mul_temp; // sfix28_En8
  wire signed [17:0] product29; // sfix18_En8
  wire signed [27:0] mul_temp_1; // sfix28_En8
  wire signed [17:0] product28; // sfix18_En8
  wire signed [27:0] mul_temp_2; // sfix28_En8
  wire signed [17:0] product27; // sfix18_En8
  wire signed [27:0] mul_temp_3; // sfix28_En8
  wire signed [17:0] product26; // sfix18_En8
  wire signed [27:0] mul_temp_4; // sfix28_En8
  wire signed [17:0] product25; // sfix18_En8
  wire signed [12:0] mulpwr2_temp_2; // sfix13
  wire signed [17:0] product23; // sfix18_En8
  wire signed [27:0] mul_temp_5; // sfix28_En8
  wire signed [17:0] product22; // sfix18_En8
  wire signed [27:0] mul_temp_6; // sfix28_En8
  wire signed [17:0] product21; // sfix18_En8
  wire signed [27:0] mul_temp_7; // sfix28_En8
  wire signed [17:0] product20; // sfix18_En8
  wire signed [27:0] mul_temp_8; // sfix28_En8
  wire signed [17:0] product19; // sfix18_En8
  wire signed [17:0] product18; // sfix18_En8
  wire signed [27:0] mul_temp_9; // sfix28_En8
  wire signed [17:0] product17; // sfix18_En8
  wire signed [27:0] mul_temp_10; // sfix28_En8
  wire signed [17:0] product16; // sfix18_En8
  wire signed [27:0] mul_temp_11; // sfix28_En8
  wire signed [17:0] product15; // sfix18_En8
  wire signed [27:0] mul_temp_12; // sfix28_En8
  wire signed [17:0] product14; // sfix18_En8
  wire signed [17:0] product13; // sfix18_En8
  wire signed [27:0] mul_temp_13; // sfix28_En8
  wire signed [17:0] product12; // sfix18_En8
  wire signed [27:0] mul_temp_14; // sfix28_En8
  wire signed [17:0] product11; // sfix18_En8
  wire signed [27:0] mul_temp_15; // sfix28_En8
  wire signed [17:0] product10; // sfix18_En8
  wire signed [27:0] mul_temp_16; // sfix28_En8
  wire signed [17:0] product8; // sfix18_En8
  wire signed [12:0] mulpwr2_temp_3; // sfix13
  wire signed [17:0] product7; // sfix18_En8
  wire signed [27:0] mul_temp_17; // sfix28_En8
  wire signed [17:0] product6; // sfix18_En8
  wire signed [27:0] mul_temp_18; // sfix28_En8
  wire signed [17:0] product5; // sfix18_En8
  wire signed [27:0] mul_temp_19; // sfix28_En8
  wire signed [17:0] product4; // sfix18_En8
  wire signed [27:0] mul_temp_20; // sfix28_En8
  wire signed [17:0] product3; // sfix18_En8
  wire signed [27:0] mul_temp_21; // sfix28_En8
  wire signed [17:0] product2; // sfix18_En8
  wire signed [12:0] mulpwr2_temp_4; // sfix13
  wire signed [20:0] product1_cast; // sfix21_En8
  wire signed [17:0] product1; // sfix18_En8
  wire signed [12:0] mulpwr2_temp_5; // sfix13
  wire signed [20:0] sum1; // sfix21_En8
  wire signed [20:0] add_signext; // sfix21_En8
  wire signed [20:0] add_signext_1; // sfix21_En8
  wire signed [21:0] add_temp; // sfix22_En8
  wire signed [20:0] sum2; // sfix21_En8
  wire signed [20:0] add_signext_2; // sfix21_En8
  wire signed [20:0] add_signext_3; // sfix21_En8
  wire signed [21:0] add_temp_1; // sfix22_En8
  wire signed [20:0] sum3; // sfix21_En8
  wire signed [20:0] add_signext_4; // sfix21_En8
  wire signed [20:0] add_signext_5; // sfix21_En8
  wire signed [21:0] add_temp_2; // sfix22_En8
  wire signed [20:0] sum4; // sfix21_En8
  wire signed [20:0] add_signext_6; // sfix21_En8
  wire signed [20:0] add_signext_7; // sfix21_En8
  wire signed [21:0] add_temp_3; // sfix22_En8
  wire signed [20:0] sum5; // sfix21_En8
  wire signed [20:0] add_signext_8; // sfix21_En8
  wire signed [20:0] add_signext_9; // sfix21_En8
  wire signed [21:0] add_temp_4; // sfix22_En8
  wire signed [20:0] sum6; // sfix21_En8
  wire signed [20:0] add_signext_10; // sfix21_En8
  wire signed [20:0] add_signext_11; // sfix21_En8
  wire signed [21:0] add_temp_5; // sfix22_En8
  wire signed [20:0] sum7; // sfix21_En8
  wire signed [20:0] add_signext_12; // sfix21_En8
  wire signed [20:0] add_signext_13; // sfix21_En8
  wire signed [21:0] add_temp_6; // sfix22_En8
  wire signed [20:0] sum8; // sfix21_En8
  wire signed [20:0] add_signext_14; // sfix21_En8
  wire signed [20:0] add_signext_15; // sfix21_En8
  wire signed [21:0] add_temp_7; // sfix22_En8
  wire signed [20:0] sum9; // sfix21_En8
  wire signed [20:0] add_signext_16; // sfix21_En8
  wire signed [20:0] add_signext_17; // sfix21_En8
  wire signed [21:0] add_temp_8; // sfix22_En8
  wire signed [20:0] sum10; // sfix21_En8
  wire signed [20:0] add_signext_18; // sfix21_En8
  wire signed [20:0] add_signext_19; // sfix21_En8
  wire signed [21:0] add_temp_9; // sfix22_En8
  wire signed [20:0] sum11; // sfix21_En8
  wire signed [20:0] add_signext_20; // sfix21_En8
  wire signed [20:0] add_signext_21; // sfix21_En8
  wire signed [21:0] add_temp_10; // sfix22_En8
  wire signed [20:0] sum12; // sfix21_En8
  wire signed [20:0] add_signext_22; // sfix21_En8
  wire signed [20:0] add_signext_23; // sfix21_En8
  wire signed [21:0] add_temp_11; // sfix22_En8
  wire signed [20:0] sum13; // sfix21_En8
  wire signed [20:0] add_signext_24; // sfix21_En8
  wire signed [20:0] add_signext_25; // sfix21_En8
  wire signed [21:0] add_temp_12; // sfix22_En8
  wire signed [20:0] sum14; // sfix21_En8
  wire signed [20:0] add_signext_26; // sfix21_En8
  wire signed [20:0] add_signext_27; // sfix21_En8
  wire signed [21:0] add_temp_13; // sfix22_En8
  wire signed [20:0] sum15; // sfix21_En8
  wire signed [20:0] add_signext_28; // sfix21_En8
  wire signed [20:0] add_signext_29; // sfix21_En8
  wire signed [21:0] add_temp_14; // sfix22_En8
  wire signed [20:0] sum16; // sfix21_En8
  wire signed [20:0] add_signext_30; // sfix21_En8
  wire signed [20:0] add_signext_31; // sfix21_En8
  wire signed [21:0] add_temp_15; // sfix22_En8
  wire signed [20:0] sum17; // sfix21_En8
  wire signed [20:0] add_signext_32; // sfix21_En8
  wire signed [20:0] add_signext_33; // sfix21_En8
  wire signed [21:0] add_temp_16; // sfix22_En8
  wire signed [20:0] sum18; // sfix21_En8
  wire signed [20:0] add_signext_34; // sfix21_En8
  wire signed [20:0] add_signext_35; // sfix21_En8
  wire signed [21:0] add_temp_17; // sfix22_En8
  wire signed [20:0] sum19; // sfix21_En8
  wire signed [20:0] add_signext_36; // sfix21_En8
  wire signed [20:0] add_signext_37; // sfix21_En8
  wire signed [21:0] add_temp_18; // sfix22_En8
  wire signed [20:0] sum20; // sfix21_En8
  wire signed [20:0] add_signext_38; // sfix21_En8
  wire signed [20:0] add_signext_39; // sfix21_En8
  wire signed [21:0] add_temp_19; // sfix22_En8
  wire signed [20:0] sum21; // sfix21_En8
  wire signed [20:0] add_signext_40; // sfix21_En8
  wire signed [20:0] add_signext_41; // sfix21_En8
  wire signed [21:0] add_temp_20; // sfix22_En8
  wire signed [20:0] sum22; // sfix21_En8
  wire signed [20:0] add_signext_42; // sfix21_En8
  wire signed [20:0] add_signext_43; // sfix21_En8
  wire signed [21:0] add_temp_21; // sfix22_En8
  wire signed [20:0] sum23; // sfix21_En8
  wire signed [20:0] add_signext_44; // sfix21_En8
  wire signed [20:0] add_signext_45; // sfix21_En8
  wire signed [21:0] add_temp_22; // sfix22_En8
  wire signed [20:0] sum24; // sfix21_En8
  wire signed [20:0] add_signext_46; // sfix21_En8
  wire signed [20:0] add_signext_47; // sfix21_En8
  wire signed [21:0] add_temp_23; // sfix22_En8
  wire signed [20:0] sum25; // sfix21_En8
  wire signed [20:0] add_signext_48; // sfix21_En8
  wire signed [20:0] add_signext_49; // sfix21_En8
  wire signed [21:0] add_temp_24; // sfix22_En8
  wire signed [20:0] sum26; // sfix21_En8
  wire signed [20:0] add_signext_50; // sfix21_En8
  wire signed [20:0] add_signext_51; // sfix21_En8
  wire signed [21:0] add_temp_25; // sfix22_En8
  wire signed [20:0] sum27; // sfix21_En8
  wire signed [20:0] add_signext_52; // sfix21_En8
  wire signed [20:0] add_signext_53; // sfix21_En8
  wire signed [21:0] add_temp_26; // sfix22_En8
  wire signed [20:0] sum28; // sfix21_En8
  wire signed [20:0] add_signext_54; // sfix21_En8
  wire signed [20:0] add_signext_55; // sfix21_En8
  wire signed [21:0] add_temp_27; // sfix22_En8
  wire signed [20:0] sum29; // sfix21_En8
  wire signed [20:0] add_signext_56; // sfix21_En8
  wire signed [20:0] add_signext_57; // sfix21_En8
  wire signed [21:0] add_temp_28; // sfix22_En8
  reg  signed [20:0] output_register; // sfix21_En8

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
        end
      end
    end // Delay_Pipeline_process


  assign mulpwr2_temp = (delay_pipeline[31]==12'b100000000000) ? $signed({1'b0, delay_pipeline[31]}) : -delay_pipeline[31];

  assign product32 = $signed({{5{mulpwr2_temp[12]}}, mulpwr2_temp});

  assign mulpwr2_temp_1 = (delay_pipeline[30]==12'b100000000000) ? $signed({1'b0, delay_pipeline[30]}) : -delay_pipeline[30];

  assign product31 = $signed({mulpwr2_temp_1[12:0], 1'b0});

  assign mul_temp = delay_pipeline[29] * coeff30;
  assign product30 = mul_temp[17:0];

  assign mul_temp_1 = delay_pipeline[28] * coeff29;
  assign product29 = mul_temp_1[17:0];

  assign mul_temp_2 = delay_pipeline[27] * coeff28;
  assign product28 = mul_temp_2[17:0];

  assign mul_temp_3 = delay_pipeline[26] * coeff27;
  assign product27 = mul_temp_3[17:0];

  assign mul_temp_4 = delay_pipeline[25] * coeff26;
  assign product26 = mul_temp_4[17:0];

  assign mulpwr2_temp_2 = (delay_pipeline[24]==12'b100000000000) ? $signed({1'b0, delay_pipeline[24]}) : -delay_pipeline[24];

  assign product25 = $signed({mulpwr2_temp_2[12:0], 2'b00});

  assign mul_temp_5 = delay_pipeline[22] * coeff23;
  assign product23 = mul_temp_5[17:0];

  assign mul_temp_6 = delay_pipeline[21] * coeff22;
  assign product22 = mul_temp_6[17:0];

  assign mul_temp_7 = delay_pipeline[20] * coeff21;
  assign product21 = mul_temp_7[17:0];

  assign mul_temp_8 = delay_pipeline[19] * coeff20;
  assign product20 = mul_temp_8[17:0];

  assign product19 = $signed({delay_pipeline[18][11:0], 5'b00000});

  assign mul_temp_9 = delay_pipeline[17] * coeff18;
  assign product18 = mul_temp_9[17:0];

  assign mul_temp_10 = delay_pipeline[16] * coeff17;
  assign product17 = mul_temp_10[17:0];

  assign mul_temp_11 = delay_pipeline[15] * coeff16;
  assign product16 = mul_temp_11[17:0];

  assign mul_temp_12 = delay_pipeline[14] * coeff15;
  assign product15 = mul_temp_12[17:0];

  assign product14 = $signed({delay_pipeline[13][11:0], 5'b00000});

  assign mul_temp_13 = delay_pipeline[12] * coeff13;
  assign product13 = mul_temp_13[17:0];

  assign mul_temp_14 = delay_pipeline[11] * coeff12;
  assign product12 = mul_temp_14[17:0];

  assign mul_temp_15 = delay_pipeline[10] * coeff11;
  assign product11 = mul_temp_15[17:0];

  assign mul_temp_16 = delay_pipeline[9] * coeff10;
  assign product10 = mul_temp_16[17:0];

  assign mulpwr2_temp_3 = (delay_pipeline[7]==12'b100000000000) ? $signed({1'b0, delay_pipeline[7]}) : -delay_pipeline[7];

  assign product8 = $signed({mulpwr2_temp_3[12:0], 2'b00});

  assign mul_temp_17 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_17[17:0];

  assign mul_temp_18 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_18[17:0];

  assign mul_temp_19 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_19[17:0];

  assign mul_temp_20 = delay_pipeline[3] * coeff4;
  assign product4 = mul_temp_20[17:0];

  assign mul_temp_21 = delay_pipeline[2] * coeff3;
  assign product3 = mul_temp_21[17:0];

  assign mulpwr2_temp_4 = (delay_pipeline[1]==12'b100000000000) ? $signed({1'b0, delay_pipeline[1]}) : -delay_pipeline[1];

  assign product2 = $signed({mulpwr2_temp_4[12:0], 1'b0});

  assign product1_cast = $signed({{3{product1[17]}}, product1});

  assign mulpwr2_temp_5 = (delay_pipeline[0]==12'b100000000000) ? $signed({1'b0, delay_pipeline[0]}) : -delay_pipeline[0];

  assign product1 = $signed({{5{mulpwr2_temp_5[12]}}, mulpwr2_temp_5});

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{3{product2[17]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[20:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{3{product3[17]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[20:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{3{product4[17]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[20:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{3{product5[17]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[20:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{3{product6[17]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[20:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{3{product7[17]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[20:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{3{product8[17]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[20:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{3{product10[17]}}, product10});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[20:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{3{product11[17]}}, product11});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[20:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{3{product12[17]}}, product12});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[20:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{3{product13[17]}}, product13});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[20:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{3{product14[17]}}, product14});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[20:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{3{product15[17]}}, product15});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[20:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{3{product16[17]}}, product16});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[20:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{3{product17[17]}}, product17});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[20:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{3{product18[17]}}, product18});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[20:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{3{product19[17]}}, product19});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[20:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{3{product20[17]}}, product20});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[20:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{3{product21[17]}}, product21});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[20:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{3{product22[17]}}, product22});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[20:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{3{product23[17]}}, product23});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[20:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{3{product25[17]}}, product25});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[20:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{3{product26[17]}}, product26});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[20:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{3{product27[17]}}, product27});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[20:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{3{product28[17]}}, product28});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[20:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{3{product29[17]}}, product29});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[20:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{3{product30[17]}}, product30});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[20:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{3{product31[17]}}, product31});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[20:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{3{product32[17]}}, product32});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[20:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum29;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // fir_50_3
