/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/TD/workspace/ADC/ip/dsp1.v
 ** Date	:	2022 03 12
 ** TD version	:	5.0.43066
\************************************************************/

`timescale 1ns / 1ps

module dsp1 ( p, a, b, cea, ceb, cepd, clk, rstan, rstbn, rstpdn );

	output [17:0] p;

	input  [8:0] a;
	input  [8:0] b;
	input  cea;
	input  ceb;
	input  cepd;
	input  clk;
	input  rstan;
	input  rstbn;
	input  rstpdn;



	EG_LOGIC_MULT #( .INPUT_WIDTH_A(9),
				.INPUT_WIDTH_B(9),
				.OUTPUT_WIDTH(18),
				.INPUTFORMAT("UNSIGNED"),
				.INPUTREGA("ENABLE"),
				.INPUTREGB("ENABLE"),
				.OUTPUTREG("ENABLE"),
				.IMPLEMENT("DSP"),
				.SRMODE("SYNC")

			)
			inst(
				.a(a),
				.b(b),
				.p(p),
				.cea(cea),
				.ceb(ceb),
				.cepd(cepd),
				.clk(clk),
				.rstan(rstan),
				.rstbn(rstbn),
				.rstpdn(rstpdn)
			);


endmodule