/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/TD/workspace/meteorolite/hardware/ip/mult.v
 ** Date	:	2022 04 06
 ** TD version	:	5.0.43066
\************************************************************/

`timescale 1ns / 1ps

module mult ( p, a, b );

	output [15:0] p;

	input  [7:0] a;
	input  [7:0] b;



	EG_LOGIC_MULT #( .INPUT_WIDTH_A(8),
				.INPUT_WIDTH_B(8),
				.OUTPUT_WIDTH(16),
				.INPUTFORMAT("UNSIGNED"),
				.INPUTREGA("DISABLE"),
				.INPUTREGB("DISABLE"),
				.OUTPUTREG("DISABLE"),
				.IMPLEMENT("DSP")
			)
			inst(
				.a(a),
				.b(b),
				.p(p),
				.cea(1'b0),
				.ceb(1'b0),
				.cepd(1'b0),
				.clk(1'b0),
				.rstan(1'b0),
				.rstbn(1'b0),
				.rstpdn(1'b0)
			);


endmodule